name: bionic_reader
description: "An application that would can convert any PDF (potentially other file types as well) and covert them into a version for bionic reading - method where all of the relevant first letters are made bold such that it makes you read faster."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core architecture
  flutter_bloc: ^9.1.1
  sqflite: ^2.2.8+4
  get_it: ^8.2.0
  equatable: ^2.0.5

  # File and path handling
  file_picker: ^10.3.3
  path_provider: ^2.0.15
  path: ^1.8.3
  # PDF processing
  flutter_pdf_text: ^0.9.0
  pdfx: ^2.5.0

  # Utilities
  uuid: ^4.2.1
  
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.2
  flutter_colorpicker: ^1.0.3 # Or the latest version
  provider: ^6.0.0 # Or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
